# 3.3 多次元配列の計算

*n = 1*

In [16]:
import numpy as np

In [17]:
A =np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [26]:
A.shape#タプルで出力

(4,)

In [27]:
A.shape[0]

4

In [28]:
np.ndim(A)#次元数

1

In [29]:
A.ndim

1

*n = 2*

In [30]:
B = np.array( [  [1,2],[3,4],[5,6]  ] )
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [31]:
B.shape

(3, 2)

In [32]:
np.ndim(B)

2

## 3.3.2 行列の内積

In [35]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [37]:
A.shape

(2, 2)

In [38]:
B.shape

(2, 2)

In [40]:
np.dot(A,B)#積

array([[19, 22],
       [43, 50]])

In [41]:
#違い
np.dot(B,A)

array([[23, 34],
       [31, 46]])

*異なる行列形状の計算*

In [42]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])

In [43]:
A.shape

(2, 3)

In [44]:
B.shape

(3, 2)

In [45]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [47]:
C = np.array([[1,2],[3,4]])
C.shape

(2, 2)

In [49]:
np.dot(A,C)#error

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [50]:
np.dot(B,C)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

## 3.3.3 NNの内積

*biasとactivation functionは省略*  

* X : node(2)
* W : weight(2x4)
* Y : node(3)

In [51]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

In [52]:
X.shape

(2,)

In [53]:
print(W)

[[1 3 5]
 [2 4 6]]


In [54]:
W.shape

(2, 3)

In [56]:
Y = np.dot(X,W)
print(Y)

[ 5 11 17]
